### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ComputeAngleBone** [stievie/ABx#53]
I did a clean build of the actual master branch.
got dlls from postgresql-11.8-2-windows-x64.exe
i did everything from build.md, install.md (Windows) client, server, thirds etc.

when i try to login or create account inside fw.exe crashes and minidump is generated.
dbtool -a acckeys dont show anything idk why

**Comment by stievie** [comment]
So I assume you're DB setup is correct, otherwise the Server wouldn't start.
Sis you copy abclient\Setup\config.xml to abclient\bin\config.xml?
Do you have the correct login host and port configured?
~~~
  <parameter name="LoginHost" type="string" value="localhost" />
  <parameter name="LoginPort" type="int" value="2748" />
~~~

Can you open the minidump in Visual Studio and see where the crash happened, or attach it to this issue please.

**Comment by ComputeAngleBone** [comment]
ye, sorry. i got some errors only when first use ./bin/dbtool -a update but everything is here, in the install u said to ignore the errors
if i try to run again say
Connected to pgsql postgres@localhost:5432
Importing directory C:\Users\John Doe\Desktop\ABx\bin/../sql
Imported 0 files
Database version is now: 37
[crashdumps.zip](https://github.com/stievie/ABx/files/5008451/crashdumps.zip)

**Comment by ComputeAngleBone** [comment]
oh my fault, i forgot to generate keygen @_@
