### ISSUE TITLE
Cert Error

### ISSUE THREAD

**Issue by pablokawan** [stievie/ABx#66]
Hmm, how i can use absadmin on windows? im getting errors at console, and when i finish the login inside the localhost
i get stuck in `https://127.0.0.1/post/login` with a `ERR_CONNECTION_ABORTED`

`[ERROR 5a8c] Application::HandleError:411 (336151574) sslv3 alert certificate unknown`

**Comment by stievie** [comment]
In https://github.com/stievie/ABx/blob/master/INSTALL.md#server point 9 you created a self signed certificate, which is used by the file server and absadmin, because both use HTTPS. You need to get your Browser to accept this self signed certificate. If you use Firefox, that's easy, click Advanced and then Accept the risk and continue.

I'm not sure how to do that in Chrome, but you can look here https://stackoverflow.com/questions/7580508/getting-chrome-to-accept-self-signed-localhost-certificate maybe there is something for you.

**Comment by pablokawan** [comment]
chrome://flags/#allow-insecure-localhost
